

```{r}
library(tidyverse)

sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_categories <- read_csv('part_categories.csv')
inventory_parts <- read_csv('inventory_parts.csv')
inventories <- read_csv('inventories.csv')
colors <- read_csv('colors.csv')

parts
part_categories

```
Joining parts and categories

```{r}
parts %>%
# Primero recibe el siguiente dataset que con el que lo quiero relacionar. la siguiente columna es el nombre de la variable que aparece en el dataset y el siguiente parametro corresponde a la columnda del segundo dataset
  inner_join(part_categories, by=c("part_cat_id"="id"))
```
Joining parts and inventories

```{r}
parts
inventory_parts
# la columna part_num esta mapeada en el dataset parts e inventory_parts con esta variable es que se crea la reclacion entre las dos tablas

parts %>%
# esto sucede cuando ambas columnas se repiten en ambas tablas
  inner_join(inventory_parts, by="part_num")

inventory_parts %>%
# el orden de las tablas no afecta el resultado que se presenta
  inner_join(parts, by="part_num")

```
Joining three tables

```{r}
sets           # nos interesa la columa set_num, esta se relaciona con inventories
inventories    #nos interesa set_num, esta se relaciona con sets

sets %>%
  inner_join(inventories, by="set_num") %>%
# ahora lo relaciono con la siguiente tabla, relaciono id de inventory_parts con inventory_id de inventories, tienen nombres diferentes
  inner_join(inventory_parts, by=c("id" = "inventory_id"))

```

```{r}
sets %>%
  inner_join(inventories, by="set_num") %>%
  inner_join(inventory_parts, by=c("id" = "inventory_id")) %>%
  inner_join(colors, by=c("color_id" = "id"), suffix=c("_set", "_color"))     # modificando name.x y name.y con suffix


```
What´s the most common color?

```{r}
sets %>%
  inner_join(inventories, by="set_num") %>%
  inner_join(inventory_parts, by=c("id" = "inventory_id")) %>%
  inner_join(colors, by=c("color_id" = "id"), suffix=c("_set", "_color")) %>%
  count(name_color) %>%
  arrange(desc(n))  # la respuesta del color mas comun es negro

```
Left and Right Joins

```{r}
inventory_parts_joined <- sets %>%
  inner_join(inventories, by="set_num") %>%
  inner_join(inventory_parts, by=c("id" = "inventory_id")) %>%
  inner_join(colors, by=c("color_id" = "id"), suffix=c("_set", "_color")) %>%
  select(set_num, part_num, color_id, quantity)

inventory_parts_joined

millenium_falcon <- inventory_parts_joined %>%
  filter(set_num == "7965-1")

star_destroyer <- inventory_parts_joined %>%
  filter(set_num == "75190-1")

# Los datos de la tabla de la izquierda millenium_falcon se preservan aunque no existan en la tabla de la derecha star_destroyer. N/A indica que ese valor no se encuentra presente en la segunda tabla.
millenium_falcon %>%
  left_join(star_destroyer, by=c("part_num", "color_id"), suffix=c("_falcon", "_star_destroyec"))   # en ambos dataset las columnas se llaman de igual manera

```
Left joining two sets by color

```{r}
millenium_falcon_colors <- millenium_falcon %>%
  group_by(color_id) %>%
  summarize(total_quantity = sum(quantity))

star_destroyer_colors <- star_destroyer %>%
  group_by(color_id) %>%
  summarize(total_quantity = sum(quantity))

# 
millenium_falcon_colors %>%
  left_join(star_destroyer_colors, by="color_id", suffix=c("_falcon", "_star_destroyer"))

```

```{r}
inventory_version_1 <- inventories %>%
  filter(version==1)

# Los datos de la tabla de la derecha inventory_version_1 se preservan aunque no existan en la tabla de la izquierda sets
sets %>%
  left_join(inventory_version_1, by="set_num") %>%
  filter(is.na(version))
  
```

Right Join

```{r}
parts %>%
  count(part_cat_id) %>%
  right_join(part_categories, by=c("part_cat_id"="id"))

```

