Grouping and summarizing

Summarizing the median life expectancy

```{r}
gapminder %>%
  summarise(medianLifeExp = median(lifeExp))   # obtengo un resultado opera la funcion a lo largo del set de datos

# Filer for 1957 then summarize the median life expentancy
gapminder %>%
  filter(year == 1957) %>%
  summarise(medianLifeExp = median(lifeExp))


gapminder %>%
  filter(year == 1957) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

```

Summarizing by year

```{r}
gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

```

Summarizing by continent

```{r}
gapminder %>%
  filter(year == 1957) %>%
  group_by(continent) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))%>%
  arrange(desc(maxGdpPercap))

```

Summarizing by continent and year

```{r}
gapminder %>%
  group_by(continent, year) %>%              # Agrupo por medio de dos variables
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))


```
Line Plots

Visualizing median life expenctancy over time

```{r}
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(medianGdpPercap = median(gdpPercap))

by_year

ggplot(by_year, aes(x=year, y=medianGdpPercap)) +
  geom_line()                 # grafica de lineas

```

```{r}
by_year_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarize(medianGdpPercap = median(gdpPercap))

ggplot(by_year_continent, aes(x=year, y=medianGdpPercap, color=continent)) +
  geom_line()

```
Bar Plots

Visualizing median GDP per capita by continent

```{r}
by_continent <- gapminder %>%
  filter(year == 1952) %>%
  group_by(continent) %>%
  summarize(medianGdpPercap = median(gdpPercap))

by_continent

ggplot(by_continent, aes (x=continent , y=medianGdpPercap)) +
  geom_col()                          # grafica de barras

```
Visualizing GDP per capita by country in Oceania

```{r}
oceania_1952 <- gapminder %>%
  filter(continent == "Oceania", year == 1952)

oceania_1952

ggplot(oceania_1952, aes(x=country, y=gdpPercap)) +
  geom_col()

```
